name: noms
version: '1.0'
summary: The versioned, forkable, syncable database
description: |
  The versioned, forkable, syncable database. 
grade: stable
confinement: strict
base: core18
parts:
  noms:
    plugin: go
    source: https://github.com/attic-labs/noms.git
    go-importpath: github.com/attic-labs/noms
    build-packages:
      - build-essential
apps:
  noms:
    command: bin/noms
    daemon: simple
    restart-condition: on-abnormal
    plugs:
      - home
      - network
      - network-bind
