// This file was generated by nomgen.
// To regenerate, run `go generate` in this package.

package main

import (
	"github.com/attic-labs/noms/ref"
	"github.com/attic-labs/noms/types"
)

// FlickrImport

type FlickrImport struct {
	m types.Map
}

func NewFlickrImport() FlickrImport {
	return FlickrImport{types.NewMap()}
}

func FlickrImportFromVal(v types.Value) FlickrImport {
	return FlickrImport{v.(types.Map)}
}

// TODO: This was going to be called Value() but it collides with root.value. We need some other place to put the built-in fields like Value() and Equals().
func (s FlickrImport) NomsValue() types.Map {
	return s.m
}

func (s FlickrImport) Equals(p FlickrImport) bool {
	return s.m.Equals(p.m)
}

func (s FlickrImport) Ref() ref.Ref {
	return s.m.Ref()
}
func (s FlickrImport) UserId() types.String {
	return s.m.Get(types.NewString("userId")).(types.String)
}

func (s FlickrImport) SetUserId(p types.String) FlickrImport {
	return FlickrImportFromVal(s.m.Set(types.NewString("userId"), p))
}
func (s FlickrImport) UserName() types.String {
	return s.m.Get(types.NewString("userName")).(types.String)
}

func (s FlickrImport) SetUserName(p types.String) FlickrImport {
	return FlickrImportFromVal(s.m.Set(types.NewString("userName"), p))
}
func (s FlickrImport) OAuthToken() types.String {
	return s.m.Get(types.NewString("oAuthToken")).(types.String)
}

func (s FlickrImport) SetOAuthToken(p types.String) FlickrImport {
	return FlickrImportFromVal(s.m.Set(types.NewString("oAuthToken"), p))
}
