// Objective-C API for talking to github.com/attic-labs/noms/iOS/noms4ios Go package.
//   gobind -lang=objc -prefix=Go github.com/attic-labs/noms/iOS/noms4ios
//
// File is generated by gobind. Do not edit.

#ifndef __GoNoms4ios_H__
#define __GoNoms4ios_H__

#include <Foundation/Foundation.h>
#include "GoUniverse.h"

FOUNDATION_EXPORT void GoNoms4iosAddImageToPhotos(NSString* url, NSString* msg, NSString* dataset);

FOUNDATION_EXPORT BOOL GoNoms4iosBlobGet(NSString* path, NSData** ret0_, NSError** error);

FOUNDATION_EXPORT void GoNoms4iosBlobPut(NSString* url, NSString* dataset);

FOUNDATION_EXPORT long GoNoms4iosCountImagesInPhotos(NSString* dataset);

FOUNDATION_EXPORT int64_t GoNoms4iosCounterGetCurrentValue(NSString* dataset);

FOUNDATION_EXPORT void GoNoms4iosCounterIncrement(NSString* dataset);

FOUNDATION_EXPORT void GoNoms4iosDsDelete(NSString* dataset);

FOUNDATION_EXPORT NSString* GoNoms4iosDsList(NSString* database);

FOUNDATION_EXPORT long GoNoms4iosPhotoIndexGetCountAtDate(NSString* dataset, long d);

FOUNDATION_EXPORT long GoNoms4iosPhotoIndexGetCountOfDates(NSString* dataset);

FOUNDATION_EXPORT long GoNoms4iosPhotoIndexGetDateByIndex(NSString* dataset, long index);

FOUNDATION_EXPORT long GoNoms4iosPhotosGetCountOfTags(NSString* dataset);

FOUNDATION_EXPORT BOOL GoNoms4iosSync(NSString* source, NSString* dest, long p2, NSError** error);

FOUNDATION_EXPORT NSString* GoNoms4iosVersion();

FOUNDATION_EXPORT BOOL GoNoms4iosWriteImageFromPhotos(NSString* dataset, long index, NSString* url, NSError** error);

#endif
