
// Objective-C API for talking to the following Go packages
//
//	github.com/attic-labs/noms/iOS/noms4ios
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Noms4ios_H__
#define __Noms4ios_H__

#include "GoNoms4ios.h"
#include "GoUniverse.h"

#endif
